name: Build all

on:
  push:
    branches:
     - test
     - release/*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - 'localization/**'
     - 'resources/**'
     - ".github/workflows/build_*.yml"
     - 'scripts/flatpak/**'

  pull_request:
    branches:
     - main
     - release/*
    paths:
     - 'deps/**'
     - 'deps_src/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - ".github/workflows/build_*.yml"
     - 'build_linux.sh'
     - 'build_release_vs2022.bat'
     - 'build_release_macos.sh'
     - 'scripts/flatpak/**'


#  schedule:
#      - cron: '0 17 * * *' # run once a day at 1 AM Singapore time (UTC+8)

  workflow_dispatch: # allows for manual dispatch
    inputs:
      build-deps-only:
        description: 'Only build dependencies (bypasses caching)'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  

jobs:
  build_linux:
    strategy:
      fail-fast: false
    # Don't run scheduled builds on forks:
    if: ${{ !cancelled() && (github.event_name != 'schedule' || github.repository == 'OrcaSlicer/OrcaSlicer') }}
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ${{ vars.SELF_HOSTED && 'orca-lnx-server' || 'ubuntu-24.04' }}
      build-deps-only: ${{ inputs.build-deps-only || false }}
    secrets: inherit
  build_windows:
    # Don't run scheduled builds on forks:
    if: ${{ !cancelled() && (github.event_name != 'schedule' || github.repository == 'OrcaSlicer/OrcaSlicer') }}
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ${{ vars.SELF_HOSTED && 'orca-win-server' || 'windows-latest' }}
      build-deps-only: ${{ inputs.build-deps-only || false }}
      force-build: ${{ github.event_name == 'schedule' }}
    secrets: inherit
  unit_tests:
    name: Unit Tests
    runs-on: ${{ vars.SELF_HOSTED && 'orca-lnx-server' || 'ubuntu-24.04' }}
    needs: build_linux
    if: ${{ !cancelled() && success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            scripts
            tests
      - name: Apt-Install Dependencies
        if: ${{ !vars.SELF_HOSTED }}
        uses: ./.github/actions/apt-install-deps
      - name: Restore Test Artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ github.sha }}-tests
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~4.3.0"  # use most recent 4.3.x version
          useLocalCache: true         # <--= Use the local cache (default is 'false').
          useCloudCache: true
      - name: Unpackage and Run Unit Tests
        timeout-minutes: 20
        run: |
          tar -xvf build_tests.tar
          scripts/run_unit_tests.sh
      - name: Upload Test Logs
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: unit-test-logs
          path: build/tests/**/*.log
      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "ctest_results.xml"
      - name: Delete Test Artifact
        if: success()
        uses: geekyeggo/delete-artifact@v6
        with:
          name: ${{ github.sha }}-tests

